- name: Terraform security scan
  # You may pin to the exact commit or the version.
  # uses: triat/terraform-security-scan@5f54224e1192fa468b93bcaecb5253679b828c8e
  uses: triat/terraform-security-scan@v2.0.2
  with:
    # Whether or not to comment on pull requests.
    tfsec_actions_comment: # optional, default is true
    # Terraform working directory.
    tfsec_actions_working_dir: # optional, default is .
    # Provide checks via , without space to exclude from run
    tfsec_exclude: # optional
    # Specify the version of tfsec to install
    tfsec_version: # optional
